var entrada =require("readline-sync")
var salariobruto = entrada.question("Qual o seu salario? ")
var fgts =(salariobruto * 0.08)
var inss =(salariobruto * 0.12)
var salarioLiquido =(salariobruto - fgts - inss)
console.log("O salario bruto é de: ", salariobruto)
console.log("O recolhimento do FGTS será: ", fgts)
console.log("O recolhimento de INSS será: ", inss)
console.log("O salario liquido este mes sera: ", salarioLiquido, "reais")
