var entrada = require("readline-sync")
var terrenoComprimento = entrada.question("Me diga o valor do comprimento de um terreno retangular: ")
var terrenoLargura = entrada.question("Me diga o valor da largura de um terreno retangular: ")
var casaComprimento =entrada.question("Qual o comprimento de uma casa construida? ")
var casaLargura =entrada.question("Qual a largura de uma casa construida? ")
var areaTotalTerreno = (terrenoComprimento * terrenoLargura)
var areaTotalCasaConstruida = (casaComprimento * casaLargura)
var resultado = (areaTotalTerreno - areaTotalCasaConstruida)
console.log("O valor da area nao construida e, ", resultado,"m")
